version: '3'
services:
  nginx:
    image: juanmagalhaes/olist-nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
      - "3000:3000"
    depends_on:
      - web
    volumes:
        - assets-volume:/static:ro
  app:
    container_name: ap01
    image: juanmagalhaes/olist-react-challenge:latest
    command: yarn serve
    depends_on:
      - web
    environment:
      - REACT_APP_API_URL=localhost:8000
    expose:
      - "3000"
  web:
    restart: always
    image: juanmagalhaes/olist-djangorest-server:latest
    container_name: dg01
    command: bash -c "
        ./wait-for-it.sh db:5432
        && ./manage.py makemigrations
        && ./manage.py migrate
        && ./manage.py create_superuser_with_password
          --username ${ADMIN_USER}
          --email ${ADMIN_EMAIL}
          --password ${ADMIN_PASSWORD}
          --noinput
          --preserve
        && gunicorn core.wsgi -b 0.0.0.0:8000
      "
    depends_on:
      - db
    expose:
      - "8000"
    environment:
      - DB_HOST=db
    volumes:
      - assets-volume:/src/static
  db:
    restart: always
    image: juanmagalhaes/olist-challenge-postgres:latest
    container_name: ps01
    ports:
      - "5432:5432"
    volumes:
      - ${PG_DATA}/postgres-data:/var/lib/postgresql/data
volumes:
  assets-volume:

